# Mac OS X Python build
# admin access required
sudo:
  required
# operating system
os:
  osx
# language used by the os
language:
  objective-c
# cache directories
cache:
  directories:
    - $HOME/.cache/pip3
# clear cache log files
before_cache:
  - rm -f $HOME/.cache/pip3/log/debug.log
python:
- "3.6"
before_install:
  - which python
  - python --version
  # pip init
  - pip3 install pytest
# command to install dependencies
install:
  - brew install ffmpeg
  - pip3 install -r requirements.txt
# command to run tests
script:
  - pytest
