sudo:
  required
os:
  osx

language: python

cache:
  directories:
    - $HOME/.pyenv_cache
    - $HOME/.cache/pip

matrix:
  include:
    - env: "PYENV_VERSION=2.7.15"
    - env: "PYENV_VERSION=3.6.6"

env:
  global:
    - PYENV_ROOT="$HOME/.pyenv"
    - PATH="$PYENV_ROOT/bin:$PATH"
    - PYTHON_BUILD_CACHE_PATH=$HOME/.pyenv_cache

install:
  - brew install ffmpeg
  - git clone https://github.com/pyenv/pyenv.git $HOME/.pyenv
  - eval "$(pyenv init -)"
  - pyenv install $PYENV_VERSION
  - pyenv global $PYENV_VERSION
  - python --version
  - pip install -r requirements.txt

script:
  - pytest
