# Mac OS X Python build
language: objective_c
python:
- "3.6"
before_install:
  # install python via brew
  - brew install python3
  # make brews python the system default
  - brew link --overwrite python3
  - which python
  - python --version
  # pip init
  - pip install pytest
# command to install dependencies
install:
  - pip install -r requirements.txt
# - pip install .
# command to run tests
script:
  - timelapse.py
